version: '3'
services:
  postgres-db:
    image: "postgres:14.11"
    container_name: "node-mentoring-program"
    environment:
      - POSTGRES_USER=node-mentoring-program
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=node-mentoring-program
    restart: always
    ports:
      - '5432:5432'